language: go
go:
  - "1.13"
  - tip
before_install:
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
install:
  - go get -t ./...
script:
  - go test -coverprofile=oauth2.coverprofile
  - go test -coverprofile=bearer.coverprofile ./bearer
  - go test -coverprofile=example.coverprofile ./example
  - go test -coverprofile=hmacsha.coverprofile ./hmacsha
  - go test -coverprofile=introspection.coverprofile ./introspection
  - go test -coverprofile=revocation.coverprofile ./revocation
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
matrix:
  allow_failures:
    - go: tip
